### ISSUE TITLE
Setup the Kanbanboard for JS Capstone

### ISSUE THREAD

**Issue by HafizMassamTabraizKhan** [HafizMassamTabraizKhan/Kanbanboard-Capstone-Project-2#21]
GitHub Project Link: https://github.com/HafizMassamTabraizKhan/Kanbanboard/projects/1

We are two partners in this project.

**Comment by Gambit142** [comment]
Hi @HafizMassamTabraizKhan @katfogy 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- Created Kanban board correctly ✔️ 
- Tasks are shared in an even manner ✔️ 
- Each task has a title, description and number of points ✔️
- Each task is assigned to a team member ✔️ 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
